const guidelineSites = [
  { name: 'Unified Web Design Standard', url: './design-guideline.html', description: '国内外43の公開デザインシステム・Webガイドラインの長所を統合した独自Webデザイン定義書。原則、Tokens、UI、UX、アクセシビリティ、実装、QA、運用までを一体化。', categories: ['日本', '公開ガイド', 'デザインシステム', 'Web', 'UI/UX', '実装', 'アクセシビリティ'] },
  { name: 'デジタル庁 DADS', url: 'https://design.digital.go.jp/dads/', description: 'デジタル庁の公開デザインシステム。デザイントークン、コンポーネント、アクセシビリティを体系化。', categories: ['日本', '公開ガイド', 'デザインシステム', 'Web'] },
  { name: 'デジタル庁 スタイルガイド', url: 'https://design.digital.go.jp/dads/guidance/style-guides/', description: '個別Webサイトのスタイルガイドをどう定義・運用するかを説明。', categories: ['日本', '公開ガイド', 'Web', 'UI/UX'] },
  { name: 'Science Tokyo Webスタイルガイド', url: 'https://design-system.isct.ac.jp/ja/website/style-guide', description: 'デザイントークン、UIコンポーネント、ページパターン、デザインリソースを公開。', categories: ['日本', '公開ガイド', 'デザインシステム', 'Web', 'Figma'] },
  { name: 'e-Gov デザインガイドライン', url: 'https://www.e-gov.go.jp/about-site/e-gov/designguidelines', description: '情報設計、UIデザイン、UIデザインパターンをまとめた政府Webガイドライン。', categories: ['日本', '公開ガイド', 'Web', 'UI/UX'] },
  { name: '東京都 Webガイドライン', url: 'https://www.metro.tokyo.lg.jp/policy/guideline', description: '東京都公式Webサイト群の品質と一貫性を支えるガイドライン。', categories: ['日本', '公開ガイド', 'Web', 'アクセシビリティ'] },

  { name: 'SmartHR Design System', url: 'https://smarthr.design/', description: '基本原則、基本要素、プロダクト、アクセシビリティ、ライティングまで横断する公開デザインシステム。', categories: ['日本', '公開ガイド', 'デザインシステム', 'UI/UX', 'アクセシビリティ'] },
  { name: 'Ameba Spindle', url: 'https://spindle.ameba.design/', description: 'Amebaのデザイン原則、カラー、タイポグラフィ、アイコン、UIコンポーネントを公開。', categories: ['日本', '公開ガイド', 'デザインシステム', 'UI/UX'] },
  { name: 'Serendie Design System', url: 'https://serendie.design/', description: '三菱電機のオープンなデザインシステム。Tokens、Components、Figma、Storybookまで展開。', categories: ['日本', '公開ガイド', 'デザインシステム', 'Figma', 'Storybook', '実装'] },
  { name: 'Ubie Vitals', url: 'https://vitals.ubie.life/', description: 'Design Principles、Tokens、Components、Layouts、Iconsをコード例付きで公開。', categories: ['日本', '公開ガイド', 'デザインシステム', 'UI/UX', '実装'] },
  { name: 'IKYU Design Guideline', url: 'https://www.ikyu.co.jp/design_guideline', description: '一休・Yahoo!トラベルのサービスデザインに関するガイドライン。', categories: ['日本', '公開ガイド', 'デザインシステム', 'Web'] },
  { name: 'Pepabo Design', url: 'https://design.pepabo.com/', description: 'GMOペパボのデザイン基盤。ブランド、プロダクトデザイン、デザイントークン等を横断。', categories: ['日本', '公開ガイド', 'デザインシステム', 'ブランド'] },
  { name: 'pixiv Charcoal', url: 'https://charcoal-web.pixiv.design/', description: 'pixivのWeb向けデザインシステム。Theme、React、Icons、Storybookなど実装資産も確認できる。', categories: ['日本', 'デザインシステム', 'Web', 'Storybook', '実装'] },
  { name: 'freee vibes', url: 'https://vibes.freee.co.jp/', description: 'freeeの業務Webアプリ向けデザインシステムとReactコンポーネント。', categories: ['日本', 'デザインシステム', 'Web', 'Storybook', '実装'] },
  { name: 'LINE Design System', url: 'https://designsystem.line.me/', description: 'Principles、Foundation、UX Guidelines、UI Components、Writingを体系化。', categories: ['日本', '公開ガイド', 'デザインシステム', 'UI/UX'] },
  { name: 'PayPay App Style Guide', url: 'https://app-style-guide.paypay.ne.jp/', description: 'Design Philosophy、Global Rule、Componentで構成されたPayPay公式スタイルガイド。', categories: ['日本', '公開ガイド', 'UI/UX', 'モバイル'] },
  { name: 'LYZON Design System', url: 'https://www.lyzon.co.jp/designsystem/document/', description: 'コーポレートサイト向け。基本原則、スタイル、UIコンポーネントを公開。', categories: ['日本', '公開ガイド', 'デザインシステム', 'Web', 'Figma'] },
  { name: 'D-EXPERIENCE DESIGN SYSTEM', url: 'https://ux.system.denso.info/', description: 'DENSOのDesign Principles、UXプロセス、ガイドラインをまとめたデザインシステム。', categories: ['日本', '公開ガイド', 'デザインシステム', 'UI/UX'] },
  { name: 'Sparkle Design', url: 'https://sparkle-design.goodpatch.com/', description: 'GoodpatchのFoundations、Themes、Components、Patternsをまとめたデザインシステム。', categories: ['日本', '公開ガイド', 'デザインシステム', '実装'] },
  { name: 'Myセブン銀行 Design System', url: 'https://my7app.design.sevenbank.co.jp/', description: 'Principles、Tone & Manner、Typography、Color、Spacing、UIパーツを詳細に定義。', categories: ['日本', '公開ガイド', 'デザインシステム', 'UI/UX'] },
  { name: 'Francfranc Design System Guidelines', url: 'https://francfranc.io/design-system-guidelines/', description: 'ブランド基礎、情報設計、ビジュアルマーケティングまで含む公開ガイドライン。', categories: ['日本', '公開ガイド', 'デザインシステム', 'ブランド', 'Web'] },
  { name: 'co-nect Brand Guideline', url: 'https://corp.co-nect.co.jp/brand-guideline/', description: 'ロゴ、カラー、タイポグラフィに加えUIパーツやVoice & Toneまで扱うブランドガイド。', categories: ['日本', '公開ガイド', 'ブランド', 'Web'] },
  { name: '揚羽 Brand Guidelines', url: 'https://brand.ageha.tv/', description: 'Purpose、Mission、VisionとビジュアルルールをWebで一体化したブランドガイドライン。', categories: ['日本', '公開ガイド', 'ブランド', 'Web'] },
  { name: 'ソシオメディア Human Interface Guidelines', url: 'https://www.sociomedia.co.jp/category/shig', description: 'Model、Interaction、PresentationなどUI設計原則を文章化したガイドライン。', categories: ['日本', '公開ガイド', 'UI/UX'] },
  { name: 'ハリマニックス WEB制作ガイドライン', url: 'https://guideline.nic-lab.jp/', description: 'Web制作の品質基準、ユーザビリティ、スタイルルールをまとめた制作ガイド。', categories: ['日本', '公開ガイド', 'Web'] },
  { name: 'フェニックスデザイン 制作ガイドライン', url: 'https://phoenix-design.co.jp/company/guideline/', description: 'Web制作の原則、要求事項、制作フローを整理した仕様書寄りのガイドライン。', categories: ['日本', '公開ガイド', 'Web'] },
  { name: 'Chatwork Brand Design System', url: 'https://brand.chatwork.com/', description: 'ブランドカラー、グラフィック、ブランド表現の基準をまとめた公開ブランドシステム。', categories: ['日本', '公開ガイド', 'ブランド'] },
  { name: 'BlueAI Design System', url: 'https://design.blueai.co.jp/ja/background', description: '複数プロダクトで共通利用するUIコンポーネントと設計背景を公開。', categories: ['日本', '公開ガイド', 'デザインシステム', 'UI/UX'] },
  { name: 'Rabee UI', url: 'https://rabeeui.com/docs', description: 'Figma Variables、UIコンポーネント、状態、Svelte/Tailwind実装をつなぐデザインシステム。', categories: ['日本', 'デザインシステム', 'Figma', '実装'] },

  { name: 'GitHub Primer', url: 'https://primer.style/', description: 'GitHubのDesign System。Foundations、Components、Patterns、Accessibility、Contentを網羅。', categories: ['海外', '公開ガイド', 'デザインシステム', 'Web', 'アクセシビリティ'] },
  { name: 'Atlassian Design System', url: 'https://atlassian.design/', description: 'Foundations、Tokens、Components、Content、Accessibilityを体系化した大規模デザインシステム。', categories: ['海外', '公開ガイド', 'デザインシステム', 'Web'] },
  { name: 'Material Design', url: 'https://m3.material.io/', description: 'GoogleのMaterial Design 3。Color、Typography、Layout、Components、Interactionの定番資料。', categories: ['海外', '公開ガイド', 'デザインシステム', 'UI/UX'] },
  { name: 'IBM Carbon Design System', url: 'https://carbondesignsystem.com/', description: 'IBMのDesign System。Guidelines、Components、Patterns、Data Visualizationまで豊富。', categories: ['海外', '公開ガイド', 'デザインシステム', '実装'] },
  { name: 'Microsoft Fluent 2', url: 'https://fluent2.microsoft.design/', description: 'MicrosoftのFluent Design System。Design Tokens、Layout、Components、Accessibilityを公開。', categories: ['海外', '公開ガイド', 'デザインシステム', 'UI/UX'] },
  { name: 'Adobe Spectrum 2', url: 'https://spectrum.adobe.com/', description: 'Adobeのデザインシステム。Foundations、Components、Content、Accessibilityを提供。', categories: ['海外', '公開ガイド', 'デザインシステム', 'アクセシビリティ'] },
  { name: 'Shopify Polaris', url: 'https://polaris.shopify.com/', description: 'Shopify製品向け。Design、Content、Components、Patternsをまとめた実務的なガイド。', categories: ['海外', '公開ガイド', 'デザインシステム', 'Web'] },
  { name: 'Salesforce Lightning Design System', url: 'https://www.lightningdesignsystem.com/', description: 'Salesforceの業務UI向けDesign System。Components、Design Tokens、Guidelinesが充実。', categories: ['海外', '公開ガイド', 'デザインシステム', '実装'] },
  { name: 'GOV.UK Design System', url: 'https://design-system.service.gov.uk/', description: '英国政府の公開Design System。Styles、Components、Patterns、Accessibilityの実例が豊富。', categories: ['海外', '公開ガイド', 'デザインシステム', 'Web', 'アクセシビリティ'] },
  { name: 'U.S. Web Design System', url: 'https://designsystem.digital.gov/', description: '米国政府のWeb Design System。Principles、Components、Patterns、Tokensを公開。', categories: ['海外', '公開ガイド', 'デザインシステム', 'Web', 'アクセシビリティ'] },
  { name: 'NHS Design System', url: 'https://service-manual.nhs.uk/design-system', description: '英国NHSのサービス向け。Styles、Components、Patterns、Contentの実践的ガイド。', categories: ['海外', '公開ガイド', 'デザインシステム', 'Web', 'アクセシビリティ'] },
  { name: 'Apple Human Interface Guidelines', url: 'https://developer.apple.com/design/human-interface-guidelines/', description: 'Apple公式のプラットフォーム設計原則、Layout、Inputs、Components等のガイド。', categories: ['海外', '公開ガイド', 'UI/UX', 'モバイル'] },
  { name: 'Ant Design', url: 'https://ant.design/docs/spec/introduce', description: 'エンタープライズWeb UI向けのDesign Values、Visual、Componentsを体系化。', categories: ['海外', '公開ガイド', 'デザインシステム', 'Web', '実装'] },
  { name: 'SAP Fiori Design Guidelines', url: 'https://experience.sap.com/fiori-design-web/', description: 'SAPの業務アプリ向け。Patterns、Floorplans、Components、UXルールを詳細に定義。', categories: ['海外', '公開ガイド', 'デザインシステム', 'UI/UX'] },
  { name: 'WAI-ARIA Authoring Practices Guide', url: 'https://www.w3.org/WAI/ARIA/apg/', description: 'アクセシブルなUIパターンの構造・キーボード操作・ARIA実装を定義する標準リファレンス。', categories: ['海外', '公開ガイド', 'アクセシビリティ', '実装'] }
];

const guidelineCategories = ['すべて', '日本', '海外', '公開ガイド', 'デザインシステム', 'Web', 'UI/UX', 'ブランド', 'Figma', 'Storybook', '実装', 'アクセシビリティ', 'モバイル'];
